name: CI

on: [push]

jobs:
  test:

    strategy:
      matrix:
        xcode: [11, 11.1, 11.2]

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Select Xcode version
      run: sudo xcode-select -s "/Applications/Xcode_${version}.app/Contents/Developer"
      env:
        version: ${{ matrix.xcode }}
    - name: Test
      run: xcodebuild -workspace SwiftTask.xcworkspace -scheme SwiftTask -configuration Debug clean build test COMPILER_INDEX_STORE_ENABLE=NO

